export default {
  POSTS_RECEIVED: 'POSTS_RECEIVED',
  SET_POST_DETAIL: 'SET_POST_DETAIL',
  POST_DATA_RECEIVED: 'POST_DATA_RECEIVED',
  UPDATE_FORM_FIELD: 'UPDATE_FORM_FIELD',

  CLEAR_FEEDBACK_BAR: 'CLEAR_FEEDBACK_BAR/app',

  LOGIN_REQUEST: 'LOGIN_REQUEST/auth',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS/auth',
  LOGIN_FAILED: 'LOGIN_FAILED/auth',
  LOGOUT: 'LOGOUT/auth',
  USER_BALANCE_RECEIVED: 'USER_BALANCE_RECEIVED/auth',

  UPDATE_COMPOSE_FIELD: 'UPDATE_COMPOSE_FIELD/compose',
  SUBMIT_POST_REQUEST: 'SUBMIT_POST_REQUEST/compose',
  SUBMIT_POST_SUCCESS: 'SUBMIT_POST_SUCCESS/compose',
  TOPICS_RECEIVED: 'TOPICS_RECEIVED/compose',

  UPDATE_COMMENT_TEXT: 'UPDATE_COMMENT_TEXT/post',
  SUBMIT_COMMENT_REQUEST: 'SUBMIT_COMMENT/post',
  SUBMIT_COMMENT_SUCCESS: 'SUBMIT_COMMENT/post',

  ACCEPT_REPLY_SUCCESS: 'ACCEPT_REPLY_SUCCESS',
  CLEAR_ACCEPTED_REPLY_SUCCESS: 'CLEAR_ACCEPTED_REPLY_SUCCESS',

  UPVOTE_SUCCESS: 'UPVOTE_SUCCESS/post',
  CLEAR_UPVOTE_SUCCESS: 'CLEAR_UPVOTE_SUCCESS/post',
  UPVOTE_POST_SUCCESS: 'UPVOTE_POST_SUCCESS/post',
  CLEAR_POST_UPVOTE_SUCCESS: 'CLEAR_UPVOTE_POST_SUCCESS/post',
  SUBMIT_POST_REPORT_SUCCESS: 'SUBMIT_POST_REPORT_SUCCESS/post',

  PROFILE_DATA_RECEIVED: 'PROFILE_DATA_RECEIVED/profile',
  SAVE_PROFILE_FIELD: 'SAVE_PROFILE_FIELD/profile',
  EDIT_PROFILE_REQUEST: 'EDIT_PROFILE_REQUEST/profile',
  EDIT_PROFILE_SUCCESS: 'EDIT_PROFILE_SUCCESS/profile',
  UPLOAD_PROFILE_IMAGE_REQUEST: 'UPLOAD_PROFILE_IMAGE_REQUEST/profile',
  UPLOAD_PROFILE_IMAGE_SUCCESS: 'UPLOAD_PROFILE_IMAGE_SUCCESS/profile',

  REPORTS_RECEIVED: 'REPORTS_RECEIVED/reports',
  POST_REMOVED: 'POST_REMOVED/reports',
  REPORT_RESOLVED: 'REPORT_RESOLVED/reports'
};
